### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by melekhove** [plainionist/TauriDotNetBridge#6]
Hi,
This is not actually an issue, but rather and attempt to communicate since there is no other ways to do that on GitHub :-)
Thank you for the interesting project! I was searching for something similar (WebView front + .Net back-end) and your project is very interesting indeed.
Also I'd like to let you know that I've found yet another interesting implementation - https://github.com/tryphotino. Take a look.
Thanks.

**Comment by RubenPX** [comment]
Wow, seems project is aqesome. I like it. Thanks for sharing 😉

**Comment by plainionist** [comment]
thx a lot for the feedback 👍😉
you can find videos about this project on my YT channel:
https://youtu.be/ZRX7jo6wb2o
https://youtu.be/CDEO9qGRw20
